#!/usr/bin/env bash
# configure nginx
# kill off all running nginx processes if any
# restart nginx

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
p-kill -9 nginx
service nginx restart
