#!/usr/bin/env bash
# script prints text an infinitely and executes a
# command when the shell receives sigterm signal
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
