#!/usr/bin/env bash
# displays Holberton School 10 times, but for the 9th 
# iteration, displays Holberton School and then Hi on a new line
num=1
while [ $num -le 10 ]; do
	echo "Holberton School"
	if [ $num -eq 9 ]
	then
		echo "Hi"
	fi
	num=$((num+1))
done
