#!/usr/bin/env bash
# install ufw: block all incoming traffic, allow ports 22, 80, 443

sudo apt-get -y install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 8080/tcp
sudo ufw reload
sudo nano /etc/default/ufw
IPV6=yes
sudo ufw disable
sudo ufw enable
