#!/usr/bin/env bash
# run web server as nginx user and not root

p-kill -9 nginx
chmod 700 /etc/nginx/nginx.conf
ufw allow 'Nginx HTTP'
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
